version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "5432:5432"

  
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    environment: 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      DB_HOST: db
      EXTERNAL_PORT: 3000
      NODE_ENV: ${NODE_ENV}